# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: sa_bd
    restart: always
    ports:
      - "3306:3306"
    environment:
#      MARIADB_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ictdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
