name: Build, Push and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v2

      # Étape 2: Se connecter à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Étape 3: Construire et pousser l'image sur Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: engelrich237/itc-backend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Étape 4: Se connecter à l'instance EC2 via SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu # ou un autre utilisateur que vous utilisez
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Clé privée SSH pour accéder à votre instance
          port: 22

          # Étape 5: Tuer le container en cours d'exécution s'il existe
          script: |
            docker stop mon-app || true
            docker rm mon-app || true
            docker pull engelrich237/itc-backend:latest
            docker run -d -p 80:8080 --name mon-app engelrich237/itc-backend:latest
